services:
  {service-name}:
    shm_size: '8gb'
    runtime: nvidia
    labels:
      - "role=development"
    deploy:
      resources:
        limits:
          memory: 14G
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        helpers: ..
      args:
        - UID=${UID:-1008}
        - GID=${GID:-1008}
    cap_add:
      - NET_ADMIN
    env_file: ~/supervisely.env
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - "~/volume:/home/devuser/volume"
      - ".:/home/devuser/{project-dir}"
    working_dir: /home/devuser/{project-dir}
    entrypoint: ["tail", "-f", "/dev/null"]
